# Generated by Django 4.1.3 on 2022-11-26 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
