# Generated by Django 4.1.3 on 2022-11-26 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('rule', models.FileField(upload_to='uploads/')),
                ('status', models.CharField(choices=[(0, 'off'), (1, 'on')], default=0, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_play1', models.IntegerField()),
                ('id_play2', models.IntegerField()),
                ('score_play1', models.IntegerField(default=0)),
                ('score_play2', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[(0, 'waiting'), (1, 'running'), (2, 'end')], default=0, max_length=1)),
                ('game', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='GAMES.game')),
            ],
        ),
    ]
