# Generated by Django 4.1.3 on 2022-11-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GAMES', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.IntegerField(choices=[(0, 'off'), (1, 'on')], default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.IntegerField(choices=[(0, 'waiting'), (1, 'running'), (2, 'end')], default=0, max_length=1),
        ),
    ]
