# Generated by Django 4.1.3 on 2022-11-26 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GAMES', '0004_alter_game_author_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='history',
            field=models.FileField(blank=True, upload_to='uploads/history/'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
