# Generated by Django 4.1.3 on 2022-11-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GAMES', '0005_match_history_alter_notification_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='password',
            field=models.CharField(default='passwd', max_length=50),
        ),
    ]
