# Generated by Django 4.1.3 on 2022-11-26 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GAMES', '0006_match_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='date_create',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='match',
            name='date_end',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GAMES.game')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
