# Generated by Django 4.1.3 on 2022-11-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GAMES', '0009_game_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='ip',
            field=models.CharField(default='localhost', max_length=200),
        ),
        migrations.AddField(
            model_name='game',
            name='port',
            field=models.IntegerField(default=80),
        ),
    ]
