# Generated by Django 4.1.3 on 2022-11-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GAMES', '0011_alter_game_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='passwd',
            field=models.TextField(default='passwd'),
        ),
    ]
